import type { PlantTemplate } from '../types';

export const PLANT_DATABASE: PlantTemplate[] = [
  {
    species: 'Monstera deliciosa',
    commonName: 'Swiss Cheese Plant',
    emoji: '🌿',
    difficulty: 'easy',
    toxicToPets: true,
    tags: ['tropical', 'large', 'popular'],
    description: 'Iconic split-leaf tropical plant that\'s forgiving and fast-growing. Great for bright indirect light.',
    defaultCareProfile: {
      wateringFrequencyDays: 7,
      lightRequirement: 'medium',
      humidityRequirement: 'medium',
      fertilizingFrequencyDays: 30,
      repottingFrequencyMonths: 18,
      trimmingFrequencyDays: 90,
    },
  },
  {
    species: 'Epipremnum aureum',
    commonName: 'Pothos',
    emoji: '🌾',
    difficulty: 'easy',
    toxicToPets: true,
    tags: ['trailing', 'low-light', 'beginner'],
    description: 'Nearly impossible to kill. Thrives in low light and irregular watering. Perfect for beginners.',
    defaultCareProfile: {
      wateringFrequencyDays: 10,
      lightRequirement: 'low',
      humidityRequirement: 'low',
      fertilizingFrequencyDays: 60,
      repottingFrequencyMonths: 24,
    },
  },
  {
    species: 'Sansevieria trifasciata',
    commonName: 'Snake Plant',
    emoji: '🌵',
    difficulty: 'easy',
    toxicToPets: true,
    tags: ['succulent-like', 'low-light', 'air-purifying', 'beginner'],
    description: 'Extremely drought-tolerant. Can survive weeks without water and very low light.',
    defaultCareProfile: {
      wateringFrequencyDays: 21,
      lightRequirement: 'low',
      humidityRequirement: 'low',
      fertilizingFrequencyDays: 60,
      repottingFrequencyMonths: 36,
    },
  },
  {
    species: 'Spathiphyllum wallisii',
    commonName: 'Peace Lily',
    emoji: '🪻',
    difficulty: 'easy',
    toxicToPets: true,
    tags: ['flowering', 'low-light', 'air-purifying'],
    description: 'One of the few flowering plants that thrives in low light. Droops dramatically when thirsty — a built-in reminder!',
    defaultCareProfile: {
      wateringFrequencyDays: 7,
      lightRequirement: 'low',
      humidityRequirement: 'high',
      fertilizingFrequencyDays: 45,
      repottingFrequencyMonths: 18,
    },
  },
  {
    species: 'Ficus lyrata',
    commonName: 'Fiddle Leaf Fig',
    emoji: '🍃',
    difficulty: 'hard',
    toxicToPets: true,
    tags: ['statement', 'tropical', 'finicky'],
    description: 'Beautiful but demanding. Hates being moved and is sensitive to drafts, inconsistent watering, and low light.',
    defaultCareProfile: {
      wateringFrequencyDays: 7,
      lightRequirement: 'high',
      humidityRequirement: 'medium',
      fertilizingFrequencyDays: 30,
      repottingFrequencyMonths: 12,
      trimmingFrequencyDays: 60,
    },
  },
  {
    species: 'Aloe barbadensis miller',
    commonName: 'Aloe Vera',
    emoji: '🌵',
    difficulty: 'easy',
    toxicToPets: true,
    tags: ['succulent', 'medicinal', 'beginner'],
    description: 'Succulent with gel-filled leaves great for minor burns. Needs very little water and loves direct sun.',
    defaultCareProfile: {
      wateringFrequencyDays: 21,
      lightRequirement: 'direct',
      humidityRequirement: 'low',
      fertilizingFrequencyDays: 60,
      repottingFrequencyMonths: 24,
    },
  },
  {
    species: 'Calathea ornata',
    commonName: 'Pinstripe Plant',
    emoji: '🌸',
    difficulty: 'hard',
    toxicToPets: false,
    tags: ['prayer plant', 'patterned leaves', 'humidity-loving'],
    description: 'Stunning pink-striped leaves that fold up at night. Demands high humidity and filtered water.',
    defaultCareProfile: {
      wateringFrequencyDays: 7,
      lightRequirement: 'low',
      humidityRequirement: 'high',
      fertilizingFrequencyDays: 30,
      repottingFrequencyMonths: 12,
      mistingFrequencyDays: 2,
    },
  },
  {
    species: 'Zamioculcas zamiifolia',
    commonName: 'ZZ Plant',
    emoji: '🌻',
    difficulty: 'easy',
    toxicToPets: true,
    tags: ['drought-tolerant', 'low-light', 'beginner'],
    description: 'Nearly indestructible. Stores water in its rhizomes and thrives on neglect.',
    defaultCareProfile: {
      wateringFrequencyDays: 14,
      lightRequirement: 'low',
      humidityRequirement: 'low',
      fertilizingFrequencyDays: 60,
      repottingFrequencyMonths: 24,
    },
  },
  {
    species: 'Chlorophytum comosum',
    commonName: 'Spider Plant',
    emoji: '🌺',
    difficulty: 'easy',
    toxicToPets: false,
    tags: ['trailing', 'air-purifying', 'pet-safe', 'beginner'],
    description: 'Fast-growing, produces cascading baby \'spiderettes\'. One of the safest plants for pets.',
    defaultCareProfile: {
      wateringFrequencyDays: 7,
      lightRequirement: 'medium',
      humidityRequirement: 'low',
      fertilizingFrequencyDays: 30,
      repottingFrequencyMonths: 12,
    },
  },
  {
    species: 'Pachira aquatica',
    commonName: 'Money Tree',
    emoji: '🌳',
    difficulty: 'medium',
    toxicToPets: false,
    tags: ['lucky', 'braided trunk', 'pet-safe'],
    description: 'Said to bring good luck and prosperity. Braided trunk is iconic. Needs bright light and thorough watering.',
    defaultCareProfile: {
      wateringFrequencyDays: 10,
      lightRequirement: 'high',
      humidityRequirement: 'medium',
      fertilizingFrequencyDays: 30,
      repottingFrequencyMonths: 24,
    },
  },
  {
    species: 'Crassula ovata',
    commonName: 'Jade Plant',
    emoji: '🌿',
    difficulty: 'easy',
    toxicToPets: true,
    tags: ['succulent', 'long-lived', 'lucky'],
    description: 'Long-lived succulent that can become a small tree. Can live for decades with minimal care.',
    defaultCareProfile: {
      wateringFrequencyDays: 14,
      lightRequirement: 'high',
      humidityRequirement: 'low',
      fertilizingFrequencyDays: 90,
      repottingFrequencyMonths: 24,
    },
  },
  {
    species: 'Hedera helix',
    commonName: 'English Ivy',
    emoji: '🌿',
    difficulty: 'medium',
    toxicToPets: true,
    tags: ['trailing', 'air-purifying', 'classic'],
    description: 'Classic trailing plant great for hanging baskets. Needs regular misting to prevent spider mites.',
    defaultCareProfile: {
      wateringFrequencyDays: 7,
      lightRequirement: 'medium',
      humidityRequirement: 'medium',
      fertilizingFrequencyDays: 30,
      repottingFrequencyMonths: 12,
      mistingFrequencyDays: 3,
    },
  },
  {
    species: 'Dracaena marginata',
    commonName: 'Dragon Tree',
    emoji: '🌴',
    difficulty: 'easy',
    toxicToPets: true,
    tags: ['architectural', 'air-purifying', 'low-water'],
    description: 'Dramatic spiky-leaved tree that tolerates low light and irregular watering.',
    defaultCareProfile: {
      wateringFrequencyDays: 14,
      lightRequirement: 'medium',
      humidityRequirement: 'low',
      fertilizingFrequencyDays: 60,
      repottingFrequencyMonths: 24,
    },
  },
  {
    species: 'Rhipsalis baccifera',
    commonName: 'Mistletoe Cactus',
    emoji: '🍑',
    difficulty: 'easy',
    toxicToPets: false,
    tags: ['epiphytic cactus', 'trailing', 'pet-safe', 'unique'],
    description: 'Unique jungle cactus with cascading stems. Unlike desert cacti, it likes humidity and indirect light.',
    defaultCareProfile: {
      wateringFrequencyDays: 10,
      lightRequirement: 'medium',
      humidityRequirement: 'medium',
      fertilizingFrequencyDays: 60,
      repottingFrequencyMonths: 24,
    },
  },
  {
    species: 'Anthurium andraeanum',
    commonName: 'Flamingo Flower',
    emoji: '🌺',
    difficulty: 'medium',
    toxicToPets: true,
    tags: ['flowering', 'tropical', 'showy'],
    description: 'Waxy, heart-shaped flowers that bloom for months. Needs bright light and high humidity.',
    defaultCareProfile: {
      wateringFrequencyDays: 7,
      lightRequirement: 'high',
      humidityRequirement: 'high',
      fertilizingFrequencyDays: 30,
      repottingFrequencyMonths: 18,
      mistingFrequencyDays: 3,
    },
  },
];

export function searchPlantDatabase(query: string): PlantTemplate[] {
  const q = query.toLowerCase();
  return PLANT_DATABASE.filter(
    (p) =>
      p.commonName.toLowerCase().includes(q) ||
      p.species.toLowerCase().includes(q) ||
      p.tags.some((t) => t.includes(q)),
  );
}
